sudo: required
services:
  - docker
before_install:
  - docker build -t vleon77/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vleon77/react-test npm test
after_success:
  - docker build -t vleon77/multi-client ./client
  - docker build -t vleon77/multi-nginx ./nginx
  - docker build -t vleon77/multi-server ./server
  - docker build -t vleon77/multi-worker ./worker
#Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push vleon77/multi-client
  - docker push vleon77/multi-nginx
  - docker push vleon77/multi-server
  - docker push vleon77/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-245851836550
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET

